### ISSUE TITLE
You may not need this validation check as you know we will get selected one by default 😀

### ISSUE THREAD

**Issue by FatefulNur** [alnahian2003/jobbar#1]
https://github.com/alnahian2003/jobbar/blob/863015811103582778d9dce5ef18e85e98466ccc/components/create-job-form.blade.php#L48C9-L52C18

**Comment by alnahian2003** [comment]
Are you sure? Isn't that a form to create a new job?

It's always considered good practice to display error messages based on the validation error.

I may be wrong, but could you please elaborate more on this?

Thanks, and have a nice day!

**Comment by FatefulNur** [comment]
To say about best practice in this scenario, I have no idea.

But I said it because, for select option we set at least one **default** value or in the migration also can hold one as well.

So we might never meet a validation message in this perspective and might reduce validation rules by deducting employment_type from Laravel Form request.

But if it's a best practice then leave as it is.

**Comment by alnahian2003** [comment]
Thanks for your input. After evaluating the discussion, I've decided to close the issue as further dialogue might not add insights. If you have more questions, feel free to reach out.

Appreciate your understanding.
